name: Ruby Unit Tests

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        backend: ['ncbo_cron', 'ncbo_cron-agraph'] # ruby runs tests with 4store backend and ruby-agraph runs with AllegroGraph backend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: copy config.rb file from template
      run:  cp config/config.test.rb config/config.rb
    - name: Build docker-compose
      run: docker-compose build
    - name: Run unit tests
      run: |
        ci_env=`bash <(curl -s https://codecov.io/env)`
        docker-compose run $ci_env -e CI --rm ${{ matrix.backend }} bundle exec rake test TESTOPTS='-v'
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        flags: unittests
        verbose: true
        fail_ci_if_error: false # optional (default = false)

